In [1]:
import numpy

In [2]:
numpy.__version__

'1.20.1'

In [4]:
nparr = numpy.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
import numpy as np

In [8]:
## test

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(10).dtype

dtype('float64')

In [11]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.full([3,5],666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [15]:
np.full((3,5),666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [16]:
np.full(shape=(10),fill_value=77.0)

array([77., 77., 77., 77., 77., 77., 77., 77., 77., 77.])

In [18]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#random number

In [21]:
np.random.randint(0,10,10)

array([5, 2, 6, 0, 2, 1, 3, 7, 0, 0])

In [22]:
np.random.randint(0,5)

4

In [24]:
np.random.randint(0,5,size=10)

array([2, 2, 0, 3, 3, 0, 2, 2, 2, 0])

In [25]:
np.random.randint(0,5,size=(3,5))

array([[2, 0, 3, 0, 3],
       [2, 4, 3, 0, 4],
       [3, 1, 2, 4, 2]])

In [27]:
np.random.random(10)

array([4.03261241e-01, 7.52212565e-01, 7.07211036e-01, 3.12397651e-04,
       3.68257363e-01, 1.75682784e-01, 7.66968768e-01, 5.44278767e-01,
       3.09856163e-01, 5.69345146e-01])

In [29]:
np.random.random([3,5])

array([[0.35914716, 0.3582201 , 0.44406187, 0.91995667, 0.73834538],
       [0.29333869, 0.2999193 , 0.31256738, 0.48603772, 0.0027618 ],
       [0.81427045, 0.20452595, 0.96624   , 0.75266104, 0.4600096 ]])

In [30]:
np.random.normal?

In [ ]:
help(np.random.normal)